from intelligraphs.errors.custom_error import DataError